CMakeLists.txt

Since the ICD loader tests don't build by default anymore there is no need to set the folder for the ICD loader tests.

only set folders for ICD loader, not for ICD loader tests

---

samples/05_spirvkernelfromfile/main.cpp

Use reserve to allocate capacity (but not fill the buffer with bytes), to avoid double allocation of the file.

Avoid double allocation in file

---

include/CL/cl2.hpp

Temporarily add guards around calls to clSetProgramReleaseCallback to eliminate a deprecated API warning until this change is upstreamed.

guard setProgramReleaseCallback to eliminate warning

---

samples/10_queueexperiments/README.md
samples/10_queueexperiments/main.cpp

* Refactors the queueexperiments sample to reduce code duplication.
* Adds support for executing a variable number of kernel executions, controllable via a command-line option.

update the queueexperiments sample to test more kernel instances

---

include/CL/opencl.hpp
samples/00_enumqueuefamilies/CMakeLists.txt
samples/00_enumqueuefamilies/README.md
samples/00_enumqueuefamilies/main.cpp
samples/CMakeLists.txt

This is a simple sample to enumerate the different queue families supported by a device.
See: [cl_intel_command_queue_families](https://www.khronos.org/registry/OpenCL/extensions/intel/cl_intel_command_queue_families.html)

add enumqueuefamilies sample

---

samples/10_queueexperiments/CMakeLists.txt
samples/10_queueexperiments/README.md
samples/10_queueexperiments/main.cpp

Adds two more scenarios to "queue experiments":
* Using queues with different "queue indices" (when [cl_intel_command_queue_families](https://www.khronos.org/registry/OpenCL/extensions/intel/cl_intel_command_queue_families.html) is supported).
* Using queues from different OpenCL contexts.

add more queue experiments

---

samples/images/00_enumimageformats/CMakeLists.txt
samples/images/00_enumimageformats/main.cpp

* compile enumimageformats for OpenCL 3.0 by default to pick up OpenCL 2.0 and newer image formats
* pick up extension image formats if they are in the headers

add more enumimageformats image channel orders

---

samples/06_ndrangekernelfromfile/CMakeLists.txt
samples/06_ndrangekernelfromfile/README.md
samples/06_ndrangekernelfromfile/main.cpp
samples/06_ndrangekernelfromfile/ndrange_sample_kernel.cl
samples/CMakeLists.txt

Adds a variant of the "kernel from file" sample that uses a non-NULL local work size.
As an "advanced option", this sample also supports separate compilation and linking using `clCompileProgram` and `clLinkProgram` instead of performing both operations in one step using `clBuildProgram`.

add ND-range kernel from file sample

---

samples/python/04_julia/julia.py

Fixed bug that was causing the local work size to be ignored in the Julia set python sample if provided.

use the local work size if provided

---

.github/workflows/build.yml
CMakeLists.txt
README.md
samples/usm/00_usmqueries/CMakeLists.txt
samples/usm/00_usmqueries/main.cpp
samples/usm/01_usmmeminfo/CMakeLists.txt
samples/usm/01_usmmeminfo/main.cpp
samples/usm/100_dmemhelloworld/CMakeLists.txt
samples/usm/100_dmemhelloworld/main.cpp
samples/usm/101_dmemlinkedlist/CMakeLists.txt
samples/usm/101_dmemlinkedlist/main.cpp
samples/usm/200_hmemhelloworld/CMakeLists.txt
samples/usm/200_hmemhelloworld/main.cpp
samples/usm/201_hmemlinkedlist/CMakeLists.txt
samples/usm/201_hmemlinkedlist/main.cpp
samples/usm/300_smemhelloworld/CMakeLists.txt
samples/usm/300_smemhelloworld/main.cpp
samples/usm/301_smemlinkedlist/CMakeLists.txt
samples/usm/301_smemlinkedlist/main.cpp
samples/usm/310_usmmigratemem/CMakeLists.txt
samples/usm/310_usmmigratemem/main.cpp
samples/usm/CMakeLists.txt
samples/usm/README.md

Switches most samples that use extensions - in particular the USM samples - to the OpenCL extension loader.
* Updated CMake files to conditionally build the USM samples only if the extension loader target is found.
* Updated READMEs to document the extension loader dependencies.
* Added CI targets to build with and without the extension loader.

integrate the OpenCL Extension Loader

---

samples/00_enumopencl/main.cpp
samples/00_enumopenclpp/main.cpp
samples/python/00_enumopencl/enumopencl.py

Prints the platform index when enumerating OpenCL platforms.
This can make it easier to determine which platform index to specify, especially on systems with many OpenCL platforms.

print the platform index when enumerating OpenCL platforms

---

layers/10_cmdbufemu/emulate.cpp

Fixes a few minor warnings discovered when compiling the samples on FreeBSD.

fix freebsd warnings

---

include/CL/opencl.hpp
samples/vulkan/00_juliavk/CMakeLists.txt
samples/vulkan/00_juliavk/README.md
samples/vulkan/00_juliavk/main.cpp
samples/vulkan/CMakeLists.txt

Updates the Vulkan sample to use external memory sharing and external semaphore sharing, when supported.
On one of my systems, this improves the performance from:
* host copy, host sync: 1100 fps
* external memory sharing, host sync: 3400 fps
* external memory, external semaphore sharing: 4400 fps
Note: be sure to use the latest drivers!
Note: still need to test Linux (but it should work in theory).

update Vulkan sample with external memory and semaphore sharing

---

samples/99_loaderinfo/CMakeLists.txt
samples/99_loaderinfo/main.cpp
samples/CMakeLists.txt

See: https://github.com/KhronosGroup/OpenCL-ICD-Loader/pull/188
This sample uses an unofficial extension to query information about the installed ICD loader, when supported.

add a simple sample that queries ICD loader info

---

samples/opengl/00_juliagl/README.md
samples/opengl/00_juliagl/main.cpp
samples/opengl/01_nbodygl/README.md
samples/opengl/01_nbodygl/main.cpp
samples/vulkan/00_juliavk/README.md
samples/vulkan/00_juliavk/main.cpp
samples/vulkan/01_nbodyvk/README.md
samples/vulkan/01_nbodyvk/main.cpp

Animate the OpenGL and Vulkan samples by default, but add an option to start with animation paused if desired.

animate the OpenGL and Vulkan samples by default

---

layers/10_cmdbufemu/README.md
layers/10_cmdbufemu/emulate.cpp
layers/10_cmdbufemu/emulate.h
layers/10_cmdbufemu/main.cpp

This PR improves handling for command buffer emulation events.  Specifically:
1. The event type for a command buffer emulation event is now properly returned (`CL_COMMAND_COMMAND_BUFFER_KHR`).
2. Event profiling for the `QUEUED`, `SUBMITTED`, and `START` times is more likely to be accurate.
Note that (2) does require event profiling to be properly implemented for barrier events, and empirically this does not seem to be happening for all OpenCL implementations.

improves handling of command buffer emulation events

---

samples/00_extendeddevicequeries/README.md
samples/00_extendeddevicequeries/main.cpp

Extends the "extendeddevicequeries" sample to query the device UUIDs and PCI bus info if the cl_khr_device_uuid or cl_khr_pci_bus_info extensions are supported.

add extended device queries for cl_khr_device_uuid and cl_khr_pci_bus_info

---

layers/00_example/main.cpp
layers/10_cmdbufemu/main.cpp
layers/11_semaemu/main.cpp

Adds support for the new `CL_LAYER_NAME` query to all of the layers in this repo - the example layer, the command buffer emulation layer, and the semaphore emulation layer.

add support for the CL_LAYER_NAME query

---

layers/10_cmdbufemu/emulate.cpp

Add proper reference counting for OpenCL objects that are used by command buffers.
See: https://github.com/KhronosGroup/OpenCL-Docs/pull/885

properly refcount objects used by command buffers

---

layers/10_cmdbufemu/emulate.cpp
samples/13_mutablecommandbuffers/main.cpp

If the passed-in queue is NULL for a mutable command, get the queue from the associated command buffer.

fix query for a mutable command queue

---

samples/00_enumopenclpp/main.cpp
samples/00_enumqueuefamilies/main.cpp
samples/00_extendeddevicequeries/main.cpp
samples/00_newqueriespp/main.cpp

In a few samples a vector of devices was being passed by value, which is inefficient.  Pass by reference, instead.

do not pass vectors of devices by value

---

layers/10_cmdbufemu/emulate.cpp
samples/12_commandbuffers/main.cpp
samples/13_mutablecommandbuffers/main.cpp

* Keeps the original kernel handle around for mutable dispatch querying purposes.
* Fixes https://github.com/bashbaug/SimpleOpenCLSamples/issues/79
* Adds support for the new `CL_COMMAND_BUFFER_CONTEXT_KHR` query.  See:
* https://github.com/KhronosGroup/OpenCL-Docs/issues/898
* https://github.com/KhronosGroup/OpenCL-Headers/pull/226

a few command buffer layer fixes

---

layers/10_cmdbufemu/emulate.cpp
layers/10_cmdbufemu/emulate.h
layers/10_cmdbufemu/main.cpp
layers/11_semaemu/emulate.cpp

Return the proper extension version from the emulation layers.
Since we support the context query we now implement extension version v0.9.2.
Also, minor refactoring to make it easier to update the versions in the future.

return the correct extension version for emulation layers

---

layers/10_cmdbufemu/main.cpp
layers/11_semaemu/main.cpp
samples/12_commandbuffers/main.cpp

Handle the case where multiple layers are enabled by chaining calls to clGetExtensionFunctionAddressForPlatform.
Currently, this will always return the emulated functions preferentially, though eventually this will need to become smarter.
Also fixes a minor typo.

properly handle the case when multiple layers are enabled

---

samples/00_extendeddevicequeries/main.cpp

Fix a copy-paste typo affecting the error message when cl_khr_pci_bus_info is not supported.

fix extendeddevicequeries typo

---

layers/10_cmdbufemu/emulate.cpp
layers/10_cmdbufemu/emulate.h
layers/10_cmdbufemu/main.cpp

fixes #89 
Adds support for recording SVM copies and fills into a command buffer.

add command buffer support for SVM copies and fills

---

.github/workflows/build.yml

Follows best practices by setting minimal permissions for GitHub actions.

set minimal permissions for GitHub actions

---

samples/python/requirements.txt

We do not need to explicitly list ipython or ipykernel since they are already dependencies of jupyterlab.

update python requirements

---

samples/images/00_enumimageformats/main.cpp

Sorting the queried image formats can make it easier to diff results across drivers and devices.

sort image formats before printing

---

samples/01_copybuffer/main.cpp
samples/02_copybufferkernel/main.cpp
samples/03_mandelbrot/main.cpp
samples/04_julia/main.cpp
samples/04_sobel/main.cpp
samples/05_kernelfromfile/main.cpp
samples/05_spirvkernelfromfile/main.cpp
samples/06_ndrangekernelfromfile/main.cpp
samples/11_semaphores/main.cpp
samples/12_commandbuffers/main.cpp
samples/12_commandbufferspp/main.cpp
samples/13_mutablecommandbuffers/main.cpp
samples/usm/100_dmemhelloworld/main.cpp
samples/usm/200_hmemhelloworld/main.cpp
samples/usm/300_smemhelloworld/main.cpp
samples/usm/310_usmmigratemem/main.cpp
samples/usm/400_sysmemhelloworld/main.cpp

Call the CommandQueue constructor directly instead of constructing a new CommandQueue and assigning it using the assignment operator.

call the CommandQueue constructor directly

---

.github/dependabot.yml

Adds a basic dependabot configuration file to check for github action version updates.

configure dependabot github actions version updates

---

layers/10_cmdbufemu/emulate.cpp

This is needed to pass the new command buffer negative tests.

validate command buffer creation flags

---

layers/10_cmdbufemu/emulate.cpp

PR #110 added support for validating command buffer ceration flags but missed a few flags for mutable dispatch.  This PR adds the missing flags.
The command buffer emulation layer doesn't support `cl_khr_command_buffer_multi_device` yet, which is why the `CL_COMMAND_BUFFER_DEVICE_SIDE_SYNC_KHR` flags is not enabled currently.

add more supported flags for validation

---

samples/vulkan/00_juliavk/main.cpp
samples/vulkan/01_nbodyvk/main.cpp

When the external memory and external semaphore extensions were finalized a few handle types were removed from the specification, so they should be removed from the source code also.

remove a few external memory and external semaphore handle types

---

include/layer_util.hpp
layers/11_semaemu/emulate.cpp

Completed during work on [CTS PR](https://github.com/KhronosGroup/OpenCL-CTS/pull/1942)

Added missing interface for CL_SEMAPHORE_DEVICE_HANDLE_LIST_KHR property

---

layers/11_semaemu/emulate.cpp

Completed during work on [CTS issue](https://github.com/KhronosGroup/OpenCL-CTS/issues/1691)

Corrected negative results of clCreateSemaphoreWithPropertiesKHR

---

include/CL/opencl.hpp

Completely removes CL_SEMAPHORE_HANDLE_D3D12_FENCE_KHR
Fixes an ifdef comment

minor updates for the OpenCL C++ bindings

---

include/CL/opencl.hpp
samples/16_floatatomics/CMakeLists.txt
samples/16_floatatomics/README.md
samples/16_floatatomics/main.cpp
samples/CMakeLists.txt

Adds a sample demonstrating how to use floating-point atomics in an OpenCL kernel.

add a float atomics sample

---

include/CL/opencl.hpp

This results in more deterministic results in the cases where a query generates an error.

initialize query results in the C++ bindings

---

samples/14_ooqcommandbuffers/main.cpp

The "ooqcommandbuffers" sample used std::chrono clocks but didn't include `<chrono>`.
For some reason this wasn't caught previously, but it's causing CI builds to fail now.

add mising chrono include

---

layers/10_cmdbufemu/emulate.cpp
layers/10_cmdbufemu/emulate.h
layers/10_cmdbufemu/main.cpp

see: https://github.com/KhronosGroup/OpenCL-Docs/pull/1292
Adds support for recording a command buffer with an in-order queue, and replaying it with an out-of-order queue.  In this case, explicit dependencies are added (via command queue barriers), to enforce the in-order behavior.
I will keep this as a draft until the spec changes are merged, at which time the reported extension version will need to be updated.

support mixed in-order recording and replay

---

samples/opengl/01_nbodygl/main.cpp
samples/vulkan/01_nbodyvk/main.cpp

Use an explicit float suffix to ensure that the nbody epsilon constant is considered a float constant.
This fixes a kernel build warning on some devices.

ensure nbody epsilon is a float constant

---

samples/06_ndrangekernelfromfile/main.cpp

When querying the compile log, we need to query the intermediate program object, not the final program object.
The final program object has not been created yet, so it doesn't have any devices associated with it yet.

query the right object for the compile log

---

layers/12_spirvqueriesemu/emulate.cpp

When the OpenCL extension [cl_khr_spirv_extended_debug_info](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#cl_khr_spirv_extended_debug_info) is supported, the `OpenCL.DebugInfo.100` SPIR-V extended instruction set must also be supported.

add a missing SPIR-V queries check for the extended debug info extension

---

layers/12_spirvqueriesemu/emulate.cpp

* Adds a missing check for SPIR-V 1.1 for the PipeStorage and SubgroupDispatch capabilities.
* Fix a copy-paste error resulting in AtomicFloat64AddEXT not being properly reported in some cases.

add a few additional missing SPIR-V query cases

---

layers/10_cmdbufemu/emulate.cpp

If there is only one command-queue associated with the command-buffer (so there are no cross-queue dependencies), and if the command-queue is an in-order queue (so there are no intra-queue dependencies), then we don't need to track dependencies within the command-buffer.

optimize command buffer dependencies

---

layers/10_cmdbufemu/README.md
layers/10_cmdbufemu/emulate.cpp
layers/10_cmdbufemu/emulate.h
layers/10_cmdbufemu/main.cpp

The command buffer emulation layer currently implements event profiling by tracking event profiling on command-queue barriers before and after command-buffer content, but some implementations do not properly implement event profiling on barriers.  As a workaround for these implementations, track event profiling on an empty kernel immediately after the command-queue barriers instead.
Because it is less efficient to use the empty kernel for event profiling (the current implementation requires a kernel compilation per command-buffer, in addition to the additional runtime cost associated with the empty kernel every time the command buffer is executed), this codepath is disabled by default, but may be enabled with an environment variable.

add the ability to use an empty kernel for command buffer profiling
