docs/env/ubuntu/19.04.md, docs/env/ubuntu/19.10.md
Exactly duplicates 18.04 instructions as the procedures are identical
=> Ubuntu 19.04 and 19.10 environment setup instructions

docs/env/ubuntu/19.10.md
=> Add instructions for adding users to the render group

include/CL/cl2.hpp, samples/usm/00_usmqueries/main.cpp, samples/usm/01_usmmeminfo/main.cpp, samples/usm/101_dmemlinkedlist/main.cpp, samples/usm/libusm/include/CL/cl_usm.h, samples/usm/libusm/src/libusm.cpp
Updates to latest USM headers.
Also updates to latest cl2.hpp.  At some point I will start pulling from the OpenCL-CLHPP repo vs. mirroring it in this repo, but not now.
=> USM Header Updates

.appveyor.yml, CMakeLists.txt
* Upgrades the required CMake version to v3.1.
* Sets the CMake project version to fix a CMake warning.
=> upgrade required CMake version to 3.1

docs/env/ubuntu/20.04.md
Mostly copy/pasted from previous iterations, but includes style
tweaks suggested by markdownlint
=> Environment instructions for Ubuntu 20.04

samples/usm/libusm/include/libusm.h, tutorials/interceptlayer/main.cpp, tutorials/interceptlayer/part0.md, tutorials/interceptlayer/part1.md
- don't include cl_ext_intel.h any more, just include cl_ext.h.
- add a warning message to the tutorial application
=> fixes a couple of minor bugs:

include/CL/opencl.hpp
Updates to the latest OpenCL-CLHPP bindings.
=> update to the latest OpenCL-CLHPP bindings

layers/10_cmdbufemu/README.md
README update, no functional changes.
=> update the command buffer layer README for mutable dispatch

samples/03_mandelbrot/bmp.hpp, samples/04_julia/bmp.hpp, samples/04_julia/main.cpp, tutorials/interceptlayer/bmp.hpp, tutorials/interceptlayer/main-part1solution.cpp, tutorials/interceptlayer/main-part2solution.cpp, tutorials/interceptlayer/main-part3solution.cpp, tutorials/interceptlayer/main-part4solution.cpp, tutorials/interceptlayer/main-part5solution.cpp, tutorials/interceptlayer/main-start.cpp, tutorials/interceptlayer/main.cpp
Fixes a few size_t-related warnings seen with some compilers for 32-bit builds.
=> fix a few warnings in 32-bit builds

include/CL/opencl.hpp, layers/10_cmdbufemu/emulate.cpp, layers/11_semaemu/CMakeLists.txt, layers/11_semaemu/README.md, layers/11_semaemu/emulate.cpp, layers/11_semaemu/emulate.h, layers/11_semaemu/main.cpp, layers/CMakeLists.txt, samples/11_semaphores/CMakeLists.txt, samples/11_semaphores/README.md, samples/11_semaphores/main.cpp, samples/CMakeLists.txt
Adds a sample and a basic emulation layer for the cl_khr_semaphore extension.
=> add a sample and a basic emulation layer for cl_khr_semaphore

layers/10_cmdbufemu/emulate.cpp
Fixes a few command buffer image issues found by CTS tests.
=> fix a few command buffer images issues found by CTS tests

samples/12_commandbuffers/main.cpp, samples/12_commandbufferspp/main.cpp, samples/13_mutablecommandbuffers/main.cpp
see: https://github.com/KhronosGroup/OpenCL-Docs/pull/885
=> remove command buffer invalid state

README.md, docs/env/ubuntu/22.04.md
Sorry for the delay in contributing this; main delta here is the PPA for the Intel compute runtime is no longer maintained.
=> Ubuntu 22.04 environment docs

.gitignore, samples/python/00_enumopencl/CMakeLists.txt, samples/python/00_enumopencl/enumopencl.ipynb, samples/python/00_enumopencl/enumopencl.py, samples/python/01_copybuffer/CMakeLists.txt, samples/python/01_copybuffer/copybuffer.ipynb, samples/python/01_copybuffer/copybuffer.py, samples/python/02_copybufferkernel/CMakeLists.txt, samples/python/02_copybufferkernel/copybufferkernel.py, samples/python/03_mandelbrot/CMakeLists.txt, samples/python/03_mandelbrot/mandelbrot.ipynb, samples/python/03_mandelbrot/mandelbrot.py, samples/python/04_julia/CMakeLists.txt, samples/python/04_julia/julia.ipynb, samples/python/04_julia/julia.py, samples/python/CMakeLists.txt, samples/python/requirements.txt
Adds Jupyter notebooks for many of the python samples.
=> add jupyter notebooks for many python samples

samples/04_julia/main.cpp, samples/04_sobel/main.cpp, tutorials/interceptlayer/main-part1solution.cpp, tutorials/interceptlayer/main-part2solution.cpp, tutorials/interceptlayer/main-part3solution.cpp, tutorials/interceptlayer/main-part4solution.cpp, tutorials/interceptlayer/main-part5solution.cpp, tutorials/interceptlayer/main-start.cpp, tutorials/interceptlayer/main.cpp
Fixes a compiler warning on Windows.
=> fixes a compiler warning

layers/10_cmdbufemu/emulate.cpp
Fixes #103
This change enables the new negative CTS test to pass.
=> add proper error checking for non-NULL mutable handles

include/CL/opencl.hpp, samples/CMakeLists.txt, samples/svm/00_svmqueries/CMakeLists.txt, samples/svm/00_svmqueries/README.md, samples/svm/00_svmqueries/main.cpp, samples/svm/100_cgsvmhelloworld/CMakeLists.txt, samples/svm/100_cgsvmhelloworld/README.md, samples/svm/100_cgsvmhelloworld/main.cpp, samples/svm/101_cgsvmlinkedlist/CMakeLists.txt, samples/svm/101_cgsvmlinkedlist/README.md, samples/svm/101_cgsvmlinkedlist/main.cpp, samples/svm/200_fgsvmhelloworld/CMakeLists.txt, samples/svm/200_fgsvmhelloworld/README.md, samples/svm/200_fgsvmhelloworld/main.cpp, samples/svm/201_fgsvmlinkedlist/CMakeLists.txt, samples/svm/201_fgsvmlinkedlist/README.md, samples/svm/201_fgsvmlinkedlist/main.cpp, samples/svm/CMakeLists.txt, samples/usm/00_usmqueries/README.md, samples/usm/00_usmqueries/main.cpp, samples/usm/README.md
* Adds several SVM samples, for both coarse-grained SVM and fine-grained SVM.
* Updates a few USM samples and documentation.
* Updates opencl.hpp - not quite in sync with the latest upsteam, but much closer.
=> add SVM samples and update USM samples

layers/11_semaemu/emulate.cpp, layers/11_semaemu/main.cpp
A few bugfixes and formatting updates.
This is enough to run (and pass) most of the semaphore CTS tests.
=> tidy up semaphore emulation

layers/11_semaemu/emulate.cpp
Completed during work on https://github.com/KhronosGroup/OpenCL-CTS/issues/1691
=> Added corrections related to negative results of wait/signal operations on semaphores

layers/11_semaemu/emulate.cpp
to be available for CL_SEMAPHORE_DEVICE_HANDLE_LIST_KHR query
=> Added default device from context

README.md
Fixes the image for the GitHub actions build status badge.
=> fix the GitHub actions build status badge

.github/workflows/build.yml
Pins GitHub actions by commit hash, as per OSSF recommendations.
=> GitHub action updates
